site_name: Targeting COVID-19 Portal
site_author: David Leon (Dawei Leng)
docs_dir: docs

markdown_extensions:
    - pymdownx.arithmatex

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://mg2.k-global-cdn.ml/extra.js

nav:
    - Home: index.md
    - COVID-19 Worldwide Clinical Trials: clinical.md
    - COVID-19 Worldwide Preclinical Studies: preclinical.md
    - COVID-19 Worldwide Publications: research_progress.md
    - COVID-19 GHDDI Data Analytics: Data_analytics.md
    - COVID-19 GHDDI Structure modeling: nCov_Structures.md
    - COVID-19 GHDDI Computational Studies: computational.md
    - COVID-19 GHDDI News: ghddi_news.md
    - COVID-19 Discussion: contact_us.md
    - COVID-19 Useful Links: useful_links.md

    #- 2019-nCoV Assay Protocals: assay.md
    - COVID-19 World Community:
      - Coronavirus Worldwide Evolution: cov_evolution.md
    #  - COVID-19 Discoveries From XXX: sample.md
    - Literature Review and Data Download:
      - Coronavirus Data Download: CoV_Experiment_Data.md
      - Coronavirus Potential Therapeutics Review: nCov_Targets.md
      - Coronavirus Review Articles: review_paper.md
    - Github History: history.md

theme: readthedocs    

plugins:
  - git-revision-date-localized:
